name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependency
      run: sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev
    - name: autogen
      run: ./autogen.sh
    - name: makedir
      run: mkdir build
    - name: configure
      working-directory: ./build
      run: ../configure --disable-wallet
    - name: make
      working-directory: ./build
      run: make
    - run: ls
      working-directory: ./build
    - name: make check
      working-directory: ./build
      run: make check
