name: C/C++ CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Gitian Build
      run: ./contrib/gitian/gitian-build.py -Dnb -o l ljzn 1.0.11.1

    - name: compress
      if: startsWith(github.ref, 'refs/tags/')
      run: tar -czf archive.tar.gz ./bitcoin-binaries

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: archive.tar.gz
