name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependency
      run: sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev libdb-dev libdb++-dev
    - name: autogen
      run: ./autogen.sh
    - name: makedir
      run: mkdir build
    - name: dependency
      working-directory: ./depends
      run: make
    - name: configure
      working-directory: ./build
      run: ../configure --enable-wallet --with-utils --with-daemon --prefix=`pwd`/depends/aarch64-linux-gnu
    - name: make
      working-directory: ./build
      run: make
    - run: ls -R
      working-directory: ./build
    - name: testing
      run: ./test/functional/test_runner.py
      working-directory: ./build
    - name: compress
      run: tar -czf archive.tar.gz ./build
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: archive.tar.gz
