name: C/C++ CI

on: push

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: dependency
      run: sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev libdb-dev libdb++-dev
    - name: autogen
      run: ./autogen.sh
    - name: makedir
      run: mkdir build

    - name: Cache Deps
      id: cache-deps
      uses: actions/cache@v2
      with:
        path: ./depends
        key: ${{ runner.os }}-deps
    - name: Dependency
      if: steps.cache-deps.outputs.cache-hit != 'true'
      working-directory: ./depends
      run: make

    - name: configure
      working-directory: ./build
      run: ../configure --enable-wallet --with-utils --with-daemon --disable-bench --enable-reduce-exports --disable-tests --prefix=`pwd`/depends/aarch64-linux-gnu
    - name: make
      working-directory: ./build
      run: make
    - run: ls -R
      working-directory: ./build
    - name: testing
      run: ./test/functional/test_runner.py
      working-directory: ./build

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
